### ISSUE TITLE
Publish to AMO

### ISSUE THREAD

**Issue by timothykim** [log69/yesscript2#1]
I'd love to see this addon be part of AMO addons.mozilla.org

I've been using it and it works great for me but it's bit annoying manually install it every time I restart firefox.

If there are any outstanding issues that you'd like to resolve before publishing, i'd love to help out.

Reference:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension

**Comment by log69** [comment]
Hi Tim, It's been there already ;)

https://addons.mozilla.org/EN-US/firefox/addon/yesscript2/

**Comment by timothykim** [comment]
weird. it didn't show up when I searched for it. Thanks!

**Comment by log69** [comment]
What version of Firefox are you using? The minimum supported version is 52.
It's supposed to show up in the list when you search for it on the Addon
page of Firefox using the keyword "yesscript2" or "yesscript" or even "yes
script". Just tested it with version 57 beta. 56 stable and 52 ESR.

Andras
