### ISSUE TITLE
yesScript2 does not works on https://accounts.google.com as yesScript does.

### ISSUE THREAD

**Issue by cloc3** [log69/yesscript2#4]
If I use yesScript version 1 on https://accounts.google.com I have an effect similar to put javascript.enable tu false in about:config (but selective for accounts.google.com).

disabling javascript in https://accounts.google.com with yesScript2 has no the same behaviour.

**Comment by log69** [comment]
It will not work because Google implemented the login page using Javascript only so disabling scripting will not let you go to the next page. There are some services that you cannot use when blocking scripts. There are a lot more though when it comes handy.

If you want to use it for only gmail then I suggest you to login using basic HTML view, search for it with keywords "gmail basic html". If not, then keep scripting enabled.

**Comment by cloc3** [comment]
I'm not a developer, but I not agree with you.

using the old version of yesScript (with firefox 56.0), the
account.google.com page was reloaded in the old login behaviour, which
does not use javascript. pay attention that accounts.google.com is
different from gmail, because it is a login manager for all google
services. In my mind, I can to performthe login without javscript and
to continue using google services with javascript.

you can check what I say setting javascript.enable to false in
about.config and to
perform a login in the old way, without using javascript. instead, is
impossible to perform a google login in html mode.


2017-11-26 17:14 GMT+01:00, Andras Horvath <notifications@github.com>:
> It will not work because Google implemented the login page using Javascript
> only so disabling scripting will not let you go to the next page. There are
> some services that you cannot use when blocking scripts. There are a lot
> more though when it comes handy.
>
> If you want to use it for only gmail then I suggest you to login using basic
> HTML view, search for it with keywords "gmail basic html". If not, then keep
> scripting enabled.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/log69/yesscript2/issues/4#issuecomment-347019605


-- 
Tra gli uomini la lingua era ormai ridivenuta un dato esterno su cui
non si era più in grado di intervenire se non inconsapevolmente e
questo è un aspetto importante della morte del metodo scientifico.

Lucio Russo - La rivoluzione dimenticata 5.5.

**Comment by log69** [comment]
I'm gonna take a more thorough investigation and reply back to you in a day or so.

**Comment by log69** [comment]
I've investigated the problem and I have to suggest you to login using the following link to get the same result as if Javascript were turned off:
https://accounts.google.com/ServiceLogin?nojavascript=1

**Comment by cloc3** [comment]
2017-11-27 0:39 GMT+01:00, Andras Horvath <notifications@github.com>:
> I've investigated the problem and I have to suggest you to login using the
> following link to get the same result as if Javascript were turned off:
> https://accounts.google.com/ServiceLogin?nojavascript=1
>

thank's.
that's a good hint for me.

anyway, I think your plugin should be able to intercept this google
redirect by itself, as was in the old yesScript version.
really this involve serious problems in developing?

**Comment by log69** [comment]
I've investigated more deeply and there are no relevant differences in the response headers and request headers of the accounts.google.com site when JS is turned on or off so currently I don't know from where it takes that it has to use the nojavascript=1 parameter so I suspend investigation for the time being.

**Comment by cloc3** [comment]
thank's a lot.
sorry if I press you again.

I cannot help you to write the plugin code, but I think that the
option nojavascript=1 is managed by google on the server side, so is
unvisible for the client.

On the https://accounts.google.com main page (without nojavascript=1
option), is present a <noscript> tag, containing the redirect link.
Is there a way to instruct the plugin to use this tag?

2017-11-27 11:52 GMT+01:00, Andras Horvath <notifications@github.com>:
> I've investigated more deeply and there are no relevant differences in the
> response headers and request headers of the accounts.google.com site when JS
> is turned on or off so currently I don't know from where it takes that it
> has to use the nojavascript=1 parameter so I suspend investigation for the
> time being.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/log69/yesscript2/issues/4#issuecomment-347146656


-- 
Tra gli uomini la lingua era ormai ridivenuta un dato esterno su cui
non si era più in grado di intervenire se non inconsapevolmente e
questo è un aspetto importante della morte del metodo scientifico.

Lucio Russo - La rivoluzione dimenticata 5.5.

**Comment by log69** [comment]
This is a good lead to track down the problem. I'll look into it and then
let you know in a day or so.

On Mon, Nov 27, 2017 at 4:42 PM, Marco Clocchiatti <notifications@github.com

**Comment by log69** [comment]
I've spent half a day trying to solve the problem. Google indeed has the noscript tag with the nojavascript=1 option in the page's header for redirection, but removing the noscript tags on-the-fly does not initiate the redirection there. It works in every other case. I have no other ideas how to make the browser believe that Javascript is turned off aside from blocking scripts to initiate the redirection so I give up at this point.

I really suggest you to use the link I mentioned earlier.

BTW I've made some recent changes to YesScript2. I fixed the syncing and added 3 states to it instead of the 2 original: no blocking (gray icon), half blocking (allowing internal and blocking external, blue icon) and full blocking (blocking internal and external too, red icon).

**Comment by cloc3** [comment]
noscript tag should be supported in no-javascript mode.
on chrome browser this feature is natively supported in chrome://settings/content/javascript and it works fine.

but you have spent your time in a transparent way and I appreciate your efforts.
anyway, yesscript remains installed in my browser :).

the only suggestion I may reccomend is to have a look how script blocking was working in old yesscript plugin.

thanks again for all that.

**Comment by log69** [comment]
No time resource for that currently.
