### ISSUE TITLE
monzoo.net

### ISSUE THREAD

**Issue by Mahabarata** [log69/yesscript2#9]
Hi,
the 2de option (half block) doesn't work on this website :
the 3 internal scripts "http://www.monzoo.net/tip/wz_tooltip.js", "http://www.monzoo.net/tip/tip_centerwindow.js" and "http://www.monzoo.net/tip/tip_balloon.js" (visible at the beginning of the <head>), which show balloons under the mouse, don't work.

I have tried on Waterfox (=Firefox 56) and Firefox 64
Best regards

**Comment by log69** [comment]
Hi, it may vary which website it works with and which it doesn't. It strongly depends on the website itself, no guarantee.

**Comment by Mahabarata** [comment]
no excuse : it is not because you addon is free that your answer can be allowed.
When I buy a car, it should be strange it works in England and not in Germany !
Your addon works or it doesn't work : when it doesn't, if it means for you that all is ok and you don't try to understand why it doesn't... looks very strange for me.
Best regards

**Comment by log69** [comment]
I kindly suggest you to read the page of the addon and what this addon tries to achieve and how and then you'll get a cleaner picture to decide if you want to use it or not.

**Comment by Mahabarata** [comment]
The pb is that you use the word 'try'.
If you know it doesn't work, don't put it on the page of addon for firefox because we spend some time to "try" it and then to delete it
--------------------------------------------
En date de : Jeu 3.1.19, Andras Horvath <notifications@github.com> a écrit :

 Objet: Re: [log69/yesscript2] monzoo.net (#9)
 À: "log69/yesscript2" <yesscript2@noreply.github.com>
 Cc: "Mahabarata" <the_mahabarata@yahoo.fr>, "Author" <author@noreply.github.com>
 Date: Jeudi 3 janvier 2019, 11h29
 
 I kindly suggest you to read the
 page of the addon and what this addon tries to achieve and
 how and then you'll get a cleaner picture to decide if
 you want to use it or not.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Mahabarata** [comment]
Hi,

I have tried to make some changes in your addon but you're right, "script-scr 'self'" doesn't work on this website even if I add an exception.
I have just installed the addon scriptsafe.
I have declare that monzoo is safe : and all works !
The scripts from inside the site works (the balloons) and the scripts from outside (the ads) are blocked.
So I have solved my problem.
But this addon is a very big one for what I need.
I really think thar yours will be better because smaller
Maybe you could look at this other addon to see how they make this "half mode" ?
Best regards
